INSERT INTO PLAYER (LOGIN, PASSWORD) VALUES ('player1', '$2a$10$GFucSgW0QXX0rQriK.Ax9O.x4obCapx3YFOGcDR8VqRObErVAMHMi');
INSERT INTO PLAYER (LOGIN, PASSWORD) VALUES ('player2', '$2a$10$GFucSgW0QXX0rQriK.Ax9O.x4obCapx3YFOGcDR8VqRObErVAMHMi');
